CUDA_VISIBLE_DEVICES=6 python -m model.train_ours3\
    --dataset_name 'herbarium_19' \
    --batch_size 128 \
    --grad_from_block 11 \
    --epochs 200 \
    --num_workers 8 \
    --use_ssb_splits False\
    --sup_weight 0.35 \
    --weight_decay 5e-5 \
    --transform 'imagenet' \
    --lr 0.1 \
    --eval_funcs 'v2' \
    --warmup_teacher_temp 0.07 \
    --teacher_temp 0.04 \
    --warmup_teacher_temp_epochs 30 \
    --memax_weight 4 \
    --exp_name Herb_OLD_ours_wo_matching \
    --split_train_val "False" \
    --imb_ratio 1 \
    --rev 'consis' \