CUDA_VISIBLE_DEVICES=2 python -m model.train_bacon \
    --est_freq 10 \
    --ce_warmup 1 \
    --alpha 0 \
    --beta 0.5 \
    --dataset_name 'places_LT' \
    --labeled_classes 182 \
    --num_workers 4 \
    --epochs 200\
    --exp_name place_bacon_200 \
    --imb_ratio 1 \
    --rev 'consis' \