CUDA_VISIBLE_DEVICES=4 python -m model.train_gcd \
    --dataset_name 'cifar100_LT' \
    --batch_size 256 \
    --grad_from_block 11 \
    --epochs 200 \
    --num_workers 8 \
    --use_ssb_splits \
    --sup_weight 0.35 \
    --weight_decay 5e-5 \
    --transform 'imagenet' \
    --lr 0.1 \
    --eval_funcs 'v2' \
    --warmup_teacher_temp 0.07 \
    --teacher_temp 0.04 \
    --warmup_teacher_temp_epochs 30 \
    --memax_weight 4 \
    --exp_name cifar100_GCD_consis2 \
    --split_train_val "False" \
    --imb_ratio 100 \
    --rev 'consis' \

