CUDA_VISIBLE_DEVICES=7 python -m model.train_ours_best_5 \
    --dataset_name 'cifar100_LT' \
    --batch_size 128 \
    --grad_from_block 11 \
    --epochs 200 \
    --num_workers 4 \
    --use_ssb_splits False\
    --sup_weight 0.35 \
    --weight_decay 5e-5 \
    --transform 'imagenet' \
    --lr 0.1 \
    --eval_funcs 'v2' \
    --warmup_teacher_temp 0.07 \
    --teacher_temp 0.04 \
    --warmup_teacher_temp_epochs 30 \
    --memax_weight 2 \
    --exp_name cifar100_ours_wu5_mm2 \
    --imb_ratio 100\
    --rev 'consis'\
    --split_train_val "False" \